# Architecture identifier.
arch = "riscv64"                                # str
# Platform identifier.
platform = "visionfive2"                        # str
# Platform package.
package = "axplat-riscv64-visionfive2"          # str

#
# Platform configs
#
[plat]
# Number of CPUs.
cpu-num = 1                                     # uint
# Base address of the whole physical memory.
phys-memory-base = 0x4000_0000                  # uint
# Size of the whole physical memory. (1G)
phys-memory-size = 0x4000_0000                  # uint
# Base physical address of the kernel image.
kernel-base-paddr = 0x4020_0000                 # uint
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_ffc0_4020_0000"     # uint
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_ffc0_0000_0000"      # uint
# Offset of bus address and phys address. some boards, the bus address is
# different from the physical address.
phys-bus-offset = 0                             # uint
# Kernel address space base.
kernel-aspace-base = "0xffff_ffc0_0000_0000"    # uint
# Kernel address space size.
kernel-aspace-size = "0x0000_003f_ffff_f000"    # uint
# Stack size on bootstrapping. (256K)
boot-stack-size = 0x40000                       # uint

#
# Device specifications
#
[devices]
# MMIO ranges with format (`base_paddr`, `size`).
mmio-ranges = [[0x0, 0x4000_0000]]  # [(uint, uint)]
# VirtIO MMIO ranges with format (`base_paddr`, `size`).
virtio-mmio-ranges = []             # [(uint, uint)]
# Base physical address of the PCIe ECAM space.
pci-ecam-base = 0x2b00_0000         # uint
# End PCI bus number.
pci-bus-end = 0xff                  # uint
# PCI device memory ranges.
pci-ranges = []                     # [(uint, uint)]

# Timer interrupt frequency in Hz.
timer-frequency = 4_000_000         # uint
# Timer interrupt num.
timer-irq = "0x8000_0000_0000_0005" # uint

# IPI interrupt num
ipi-irq = "0x8000_0000_0000_0001"   # uint

# VisionFive 2 RTC
rtc-paddr = 0x1704_0000             # uint

# plic: interrupt-controller@c000000 {
#     compatible = "starfive,jh7110-plic", "sifive,plic-1.0.0";
#     reg = <0x0 0xc000000 0x0 0x4000000>;
#     interrupts-extended = <&cpu0_intc 11>,
#                     <&cpu1_intc 11>, <&cpu1_intc 9>,
#                     <&cpu2_intc 11>, <&cpu2_intc 9>,
#                     <&cpu3_intc 11>, <&cpu3_intc 9>,
#                     <&cpu4_intc 11>, <&cpu4_intc 9>;
#     interrupt-controller;
#     #interrupt-cells = <1>;
#     #address-cells = <0>;
#     riscv,ndev = <136>;
# };
plic-paddr = 0x0c00_0000            # uint

# uart0: serial@10000000 {
#     compatible = "starfive,jh7110-uart", "snps,dw-apb-uart";
#     reg = <0x0 0x10000000 0x0 0x10000>;
#     clocks = <&syscrg JH7110_SYSCLK_UART0_CORE>,
#             <&syscrg JH7110_SYSCLK_UART0_APB>;
#     clock-names = "baudclk", "apb_pclk";
#     resets = <&syscrg JH7110_SYSRST_UART0_APB>,
#             <&syscrg JH7110_SYSRST_UART0_CORE>;
#     interrupts = <32>;
#     reg-io-width = <4>;
#     reg-shift = <2>;
#     status = "disabled";
# };
uart-paddr = 0x1000_0000            # uint
uart-irq = 0x20                     # uint

# mmc1: mmc@16020000 {
#     compatible = "starfive,jh7110-mmc";
#     reg = <0x0 0x16020000 0x0 0x10000>;
#     clocks = <&syscrg JH7110_SYSCLK_SDIO1_AHB>,
#             <&syscrg JH7110_SYSCLK_SDIO1_SDCARD>;
#     clock-names = "biu","ciu";
#     resets = <&syscrg JH7110_SYSRST_SDIO1_AHB>;
#     reset-names = "reset";
#     interrupts = <75>;
#     fifo-depth = <32>;
#     fifo-watermark-aligned;
#     data-addr = <0>;
#     starfive,sysreg = <&sys_syscon 0x9c 0x1 0x3e>;
#     status = "disabled";
# };
sdmmc-paddr = 0x1602_0000           # uint
